import { Game, SportsbookOdds, LineMovement, PlayerProp, Pick, Bet, PricingPlan } from './types';

export const mockGames: Game[] = [
  {
    id: '1',
    sport: 'NFL',
    league: 'NFL',
    homeTeam: { name: 'Kansas City Chiefs', abbreviation: 'KC', record: '11-4' },
    awayTeam: { name: 'Buffalo Bills', abbreviation: 'BUF', record: '10-5' },
    date: '2025-01-12',
    time: '4:25 PM ET',
    homeSpread: -3.5,
    awaySpread: 3.5,
    homeML: -175,
    awayML: +148,
    total: 51.5,
    overOdds: -110,
    underOdds: -110,
    status: 'upcoming',
  },
  {
    id: '2',
    sport: 'NBA',
    league: 'NBA',
    homeTeam: { name: 'Boston Celtics', abbreviation: 'BOS', record: '32-10' },
    awayTeam: { name: 'Golden State Warriors', abbreviation: 'GSW', record: '22-20' },
    date: '2025-01-12',
    time: '7:30 PM ET',
    homeSpread: -8.5,
    awaySpread: 8.5,
    homeML: -350,
    awayML: +280,
    total: 224.5,
    overOdds: -110,
    underOdds: -110,
    status: 'upcoming',
  },
  {
    id: '3',
    sport: 'NFL',
    league: 'NFL',
    homeTeam: { name: 'San Francisco 49ers', abbreviation: 'SF', record: '9-6' },
    awayTeam: { name: 'Los Angeles Rams', abbreviation: 'LAR', record: '10-5' },
    date: '2025-01-12',
    time: '8:20 PM ET',
    homeSpread: -2.5,
    awaySpread: 2.5,
    homeML: -140,
    awayML: +118,
    total: 48.5,
    overOdds: -115,
    underOdds: -105,
    status: 'upcoming',
  },
  {
    id: '4',
    sport: 'NBA',
    league: 'NBA',
    homeTeam: { name: 'Los Angeles Lakers', abbreviation: 'LAL', record: '20-22' },
    awayTeam: { name: 'Denver Nuggets', abbreviation: 'DEN', record: '27-15' },
    date: '2025-01-12',
    time: '9:00 PM ET',
    homeSpread: 5.5,
    awaySpread: -5.5,
    homeML: +195,
    awayML: -240,
    total: 228.5,
    overOdds: -110,
    underOdds: -110,
    status: 'live',
    homeScore: 54,
    awayScore: 61,
  },
  {
    id: '5',
    sport: 'NHL',
    league: 'NHL',
    homeTeam: { name: 'Florida Panthers', abbreviation: 'FLA', record: '25-14-3' },
    awayTeam: { name: 'Toronto Maple Leafs', abbreviation: 'TOR', record: '23-16-2' },
    date: '2025-01-12',
    time: '7:00 PM ET',
    homeSpread: -1.5,
    awaySpread: 1.5,
    homeML: -145,
    awayML: +122,
    total: 6.5,
    overOdds: -118,
    underOdds: -102,
    status: 'upcoming',
  },
  {
    id: '6',
    sport: 'CBB',
    league: 'NCAAB',
    homeTeam: { name: 'Duke Blue Devils', abbreviation: 'DUKE', record: '15-2' },
    awayTeam: { name: 'North Carolina Tar Heels', abbreviation: 'UNC', record: '12-5' },
    date: '2025-01-13',
    time: '9:00 PM ET',
    homeSpread: -5.5,
    awaySpread: 5.5,
    homeML: -220,
    awayML: +182,
    total: 156.5,
    overOdds: -110,
    underOdds: -110,
    status: 'upcoming',
  },
];

export const mockSportsbookOdds: SportsbookOdds[] = [
  {
    book: 'DraftKings',
    logo: 'DK',
    homeSpread: -3.5,
    homeSpreadOdds: -110,
    awaySpread: 3.5,
    awaySpreadOdds: -110,
    homeML: -175,
    awayML: +148,
    total: 51.5,
    overOdds: -110,
    underOdds: -110,
  },
  {
    book: 'FanDuel',
    logo: 'FD',
    homeSpread: -3.5,
    homeSpreadOdds: -108,
    awaySpread: 3.5,
    awaySpreadOdds: -112,
    homeML: -178,
    awayML: +150,
    total: 51.5,
    overOdds: -112,
    underOdds: -108,
  },
  {
    book: 'BetMGM',
    logo: 'MGM',
    homeSpread: -3,
    homeSpreadOdds: -115,
    awaySpread: 3,
    awaySpreadOdds: -105,
    homeML: -170,
    awayML: +142,
    total: 52,
    overOdds: -110,
    underOdds: -110,
  },
  {
    book: 'Caesars',
    logo: 'CZR',
    homeSpread: -3.5,
    homeSpreadOdds: -110,
    awaySpread: 3.5,
    awaySpreadOdds: -110,
    homeML: -180,
    awayML: +152,
    total: 51,
    overOdds: -108,
    underOdds: -112,
  },
  {
    book: 'PointsBet',
    logo: 'PB',
    homeSpread: -4,
    homeSpreadOdds: -105,
    awaySpread: 4,
    awaySpreadOdds: -115,
    homeML: -172,
    awayML: +145,
    total: 51.5,
    overOdds: -110,
    underOdds: -110,
  },
  {
    book: 'bet365',
    logo: 'B365',
    homeSpread: -3.5,
    homeSpreadOdds: -112,
    awaySpread: 3.5,
    awaySpreadOdds: -108,
    homeML: -175,
    awayML: +148,
    total: 51.5,
    overOdds: -115,
    underOdds: -105,
  },
];

export const mockLineMovement: LineMovement[] = [
  { timestamp: '09:00', spread: -2, total: 50, homeML: -155 },
  { timestamp: '10:00', spread: -2.5, total: 50.5, homeML: -160 },
  { timestamp: '11:00', spread: -3, total: 50.5, homeML: -165 },
  { timestamp: '12:00', spread: -3, total: 51, homeML: -168 },
  { timestamp: '13:00', spread: -3.5, total: 51, homeML: -170 },
  { timestamp: '14:00', spread: -3.5, total: 51.5, homeML: -172 },
  { timestamp: '15:00', spread: -3.5, total: 51.5, homeML: -175 },
  { timestamp: '16:00', spread: -3.5, total: 51.5, homeML: -175 },
];

export const mockPlayerProps: PlayerProp[] = [
  {
    id: '1',
    player: 'Patrick Mahomes',
    team: 'KC',
    opponent: 'vs BUF',
    sport: 'NFL',
    market: 'Pass Yards',
    line: 287.5,
    overOdds: -115,
    underOdds: -105,
    projection: 312.4,
    edge: 8.2,
    position: 'QB',
    gameTime: 'Sun 4:25 PM',
  },
  {
    id: '2',
    player: 'Travis Kelce',
    team: 'KC',
    opponent: 'vs BUF',
    sport: 'NFL',
    market: 'Receiving Yards',
    line: 64.5,
    overOdds: -110,
    underOdds: -110,
    projection: 78.3,
    edge: 12.6,
    position: 'TE',
    gameTime: 'Sun 4:25 PM',
  },
  {
    id: '3',
    player: 'Jaylen Brown',
    team: 'BOS',
    opponent: 'vs GSW',
    sport: 'NBA',
    market: 'Points',
    line: 24.5,
    overOdds: -118,
    underOdds: -102,
    projection: 27.8,
    edge: 9.4,
    position: 'SG',
    gameTime: 'Sun 7:30 PM',
  },
  {
    id: '4',
    player: 'Stephen Curry',
    team: 'GSW',
    opponent: '@ BOS',
    sport: 'NBA',
    market: '3-Pointers Made',
    line: 4.5,
    overOdds: +105,
    underOdds: -128,
    projection: 5.2,
    edge: 7.8,
    position: 'PG',
    gameTime: 'Sun 7:30 PM',
  },
  {
    id: '5',
    player: 'Josh Allen',
    team: 'BUF',
    opponent: '@ KC',
    sport: 'NFL',
    market: 'Pass Touchdowns',
    line: 2.5,
    overOdds: -125,
    underOdds: +105,
    projection: 2.9,
    edge: 6.3,
    position: 'QB',
    gameTime: 'Sun 4:25 PM',
  },
  {
    id: '6',
    player: 'Jayson Tatum',
    team: 'BOS',
    opponent: 'vs GSW',
    sport: 'NBA',
    market: 'Points + Rebounds',
    line: 38.5,
    overOdds: -112,
    underOdds: -108,
    projection: 42.1,
    edge: 10.1,
    position: 'SF',
    gameTime: 'Sun 7:30 PM',
  },
  {
    id: '7',
    player: 'Christian McCaffrey',
    team: 'SF',
    opponent: 'vs LAR',
    sport: 'NFL',
    market: 'Rush + Rec Yards',
    line: 118.5,
    overOdds: -108,
    underOdds: -112,
    projection: 132.7,
    edge: 11.4,
    position: 'RB',
    gameTime: 'Sun 8:20 PM',
  },
  {
    id: '8',
    player: 'Nikola Jokic',
    team: 'DEN',
    opponent: '@ LAL',
    sport: 'NBA',
    market: 'Rebounds',
    line: 11.5,
    overOdds: -115,
    underOdds: -105,
    projection: 13.2,
    edge: 9.8,
    position: 'C',
    gameTime: 'Sun 9:00 PM',
  },
];

export const mockPicks: Pick[] = [
  {
    id: '1',
    sport: 'NFL',
    league: 'NFL',
    game: 'BUF @ KC',
    pick: 'Kansas City Chiefs -3.5',
    market: 'Spread',
    odds: -110,
    units: 2,
    confidence: 82,
    analysis: 'Chiefs have covered 7 of last 9 at home. Bills defense has been leaky against elite QBs in January. Mahomes thrives in big-game spots — trust the process here.',
    analyst: 'Kyle Covers',
    record: '68-42 ATS',
    date: 'Jan 12',
    result: 'pending',
  },
  {
    id: '2',
    sport: 'NBA',
    league: 'NBA',
    game: 'GSW @ BOS',
    pick: 'Boston Celtics -8.5',
    market: 'Spread',
    odds: -110,
    units: 1.5,
    confidence: 74,
    analysis: "Celtics are 18-4 at home this season and Warriors are 6-14 on the road. Boston's defense ranks 2nd in the league while GSW has been inconsistent without their full roster.",
    analyst: 'The Sharp',
    record: '55-38 ATS',
    date: 'Jan 12',
    result: 'pending',
  },
  {
    id: '3',
    sport: 'NFL',
    league: 'NFL',
    game: 'SF vs LAR',
    pick: 'Under 48.5',
    market: 'Total',
    odds: -105,
    units: 2,
    confidence: 78,
    analysis: "Two of the best defenses in the NFC. Weather forecast shows 20mph winds in Santa Clara. Both teams have gone under in 4 of last 5 meetings. This is a classic grind-it-out divisional game.",
    analyst: 'LineBreaker',
    record: '61-39 O/U',
    date: 'Jan 12',
    result: 'pending',
  },
  {
    id: '4',
    sport: 'NBA',
    league: 'NBA',
    game: 'DEN @ LAL',
    pick: 'Denver Nuggets -5.5',
    market: 'Spread',
    odds: -110,
    units: 1,
    confidence: 68,
    analysis: 'Jokic is averaging 32 points over his last 5 games. Lakers are banged up with multiple starters questionable. Nuggets have won 8 straight when Jokic posts 30+.',
    analyst: 'Kyle Covers',
    record: '68-42 ATS',
    date: 'Jan 12',
    result: 'win',
  },
  {
    id: '5',
    sport: 'NFL',
    league: 'NFL',
    game: 'BUF @ KC',
    pick: 'Josh Allen Over 2.5 TDs',
    market: 'Player Prop',
    odds: -125,
    units: 1,
    confidence: 71,
    analysis: "Allen has thrown 3+ TDs in 5 of his last 7 games. Kansas City's secondary has allowed the 4th most passing TDs this season. Allen is motivated in a revenge spot.",
    analyst: 'PropShark',
    record: '72-48 Props',
    date: 'Jan 12',
    result: 'pending',
  },
  {
    id: '6',
    sport: 'NHL',
    league: 'NHL',
    game: 'TOR @ FLA',
    pick: 'Florida Panthers ML',
    market: 'Moneyline',
    odds: -145,
    units: 2,
    confidence: 79,
    analysis: "Panthers are the defending champs and are 15-4 at home this season. Sergei Bobrovsky has been elite between the pipes. Toronto is 3-8 on the road against playoff teams.",
    analyst: 'IceEdge',
    record: '44-28 NHL',
    date: 'Jan 12',
    result: 'loss',
  },
];

export const mockBets: Bet[] = [
  {
    id: '1',
    date: 'Jan 12',
    game: 'DEN @ LAL',
    pick: 'Nuggets -5.5',
    market: 'Spread',
    odds: -110,
    units: 2,
    book: 'DraftKings',
    result: 'win',
    profit: 1.82,
    sport: 'NBA',
    league: 'NBA',
    tags: ['spread', 'nba'],
  },
  {
    id: '2',
    date: 'Jan 11',
    game: 'PHI vs DAL',
    pick: 'Eagles -7',
    market: 'Spread',
    odds: -110,
    units: 3,
    book: 'FanDuel',
    result: 'win',
    profit: 2.73,
    sport: 'NFL',
    league: 'NFL',
    tags: ['spread', 'nfl'],
  },
  {
    id: '3',
    date: 'Jan 11',
    game: 'MIA @ CHI',
    pick: 'Over 215.5',
    market: 'Total',
    odds: -110,
    units: 1,
    book: 'BetMGM',
    result: 'loss',
    profit: -1,
    sport: 'NBA',
    league: 'NBA',
    tags: ['total', 'nba'],
  },
  {
    id: '4',
    date: 'Jan 10',
    game: 'NYR @ BOS',
    pick: 'Bruins ML',
    market: 'Moneyline',
    odds: -162,
    units: 2,
    book: 'Caesars',
    result: 'win',
    profit: 1.23,
    sport: 'NHL',
    league: 'NHL',
    tags: ['ml', 'nhl'],
  },
  {
    id: '5',
    date: 'Jan 10',
    game: 'SF vs ARI',
    pick: '49ers -13.5',
    market: 'Spread',
    odds: -110,
    units: 2,
    book: 'DraftKings',
    result: 'loss',
    profit: -2,
    sport: 'NFL',
    league: 'NFL',
    tags: ['spread', 'nfl'],
  },
  {
    id: '6',
    date: 'Jan 9',
    game: 'Nikola Jokic',
    pick: 'Rebounds Over 11.5',
    market: 'Player Prop',
    odds: -115,
    units: 1.5,
    book: 'FanDuel',
    result: 'win',
    profit: 1.30,
    sport: 'NBA',
    league: 'NBA',
    tags: ['prop', 'nba'],
  },
  {
    id: '7',
    date: 'Jan 9',
    game: 'GB vs MIN',
    pick: 'Under 45',
    market: 'Total',
    odds: -108,
    units: 2,
    book: 'PointsBet',
    result: 'push',
    profit: 0,
    sport: 'NFL',
    league: 'NFL',
    tags: ['total', 'nfl'],
  },
  {
    id: '8',
    date: 'Jan 8',
    game: 'LAC @ OKC',
    pick: 'Thunder -4',
    market: 'Spread',
    odds: -110,
    units: 2,
    book: 'DraftKings',
    result: 'win',
    profit: 1.82,
    sport: 'NBA',
    league: 'NBA',
    tags: ['spread', 'nba'],
  },
  {
    id: '9',
    date: 'Jan 8',
    game: 'Patrick Mahomes',
    pick: 'Pass Yards Over 287.5',
    market: 'Player Prop',
    odds: -115,
    units: 1,
    book: 'BetMGM',
    result: 'loss',
    profit: -1,
    sport: 'NFL',
    league: 'NFL',
    tags: ['prop', 'nfl'],
  },
  {
    id: '10',
    date: 'Jan 7',
    game: 'VGK @ EDM',
    pick: 'Under 6',
    market: 'Total',
    odds: -112,
    units: 1.5,
    book: 'Caesars',
    result: 'win',
    profit: 1.34,
    sport: 'NHL',
    league: 'NHL',
    tags: ['total', 'nhl'],
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    name: 'Free',
    price: 0,
    billingPeriod: 'forever',
    description: 'Get started with basic odds tracking and analysis tools.',
    features: [
      'Live odds from 3 sportsbooks',
      'Basic line movement',
      'Public betting percentages',
      'Today\'s top 3 picks',
      'Limited props access',
      'Community access',
    ],
    highlighted: false,
    cta: 'Get Started Free',
  },
  {
    name: 'Pro',
    price: 29,
    billingPeriod: 'month',
    description: 'The full suite for serious bettors who want the edge.',
    features: [
      'Live odds from 15+ sportsbooks',
      'Full line movement history',
      'Sharp money & steam moves',
      'Unlimited picks & best bets',
      'Full props database + edge scores',
      'Advanced bet tracker & analytics',
      'Injury & weather alerts',
      'Model projections',
      'Discord community access',
      'Email & push notifications',
    ],
    highlighted: true,
    cta: 'Start Pro – 7 Days Free',
  },
  {
    name: 'Elite',
    price: 79,
    billingPeriod: 'month',
    description: 'For professional-level bettors who need every advantage.',
    features: [
      'Everything in Pro',
      'Live in-game odds tracker',
      'CLV (Closing Line Value) tracker',
      'Arbitrage & middle finder',
      'Custom alerts & filters',
      'API access',
      'VIP Discord channel',
      'Priority support',
      'Bankroll management tools',
      'Weekly Q&A with analysts',
    ],
    highlighted: false,
    cta: 'Go Elite',
  },
];
